import{a as m,S as d,i as s}from"./assets/vendor-CYMld6vM.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const y="52368753-eba0a00d68a5190bbbbc4e7af",g="https://pixabay.com/api/";function h(r){const o={key:y,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:16};return m.get(g,{params:o}).then(n=>n.data)}const u=document.querySelector(".gallery"),b=new d(".gallery a",{captionsData:"alt",captionDelay:250});function L(r){const o=r.map(({webformatURL:n,largeImageURL:i,tags:e,likes:t,views:a,comments:p,downloads:f})=>`<li class="gallery-item">
        <a class="gallery-link" href="${i}">
        <img class="img-item" src="${n}" alt="${e}"/>
        </a>
        <p>Likes <span>${t}</span></p>
        <p>View <span>${a}</span></p>
        <p>Comments <span>${p}</span></p>
        <p>Downloads <span>${f}</span></p>
        </li>`).join("");u.innerHTML=o,b.refresh()}function l(){u.innerHTML=""}function S(r){r.style.display="block"}function q(r){r.style.display="none"}document.querySelector(".gallery");const w=document.querySelector(".form"),E=document.querySelector('[name="search-text"]'),c=document.querySelector(".loader");w.addEventListener("submit",function(r){r.preventDefault();const o=E.value.trim();if(o===""){s.warning({title:"Caution",message:"You forgot important data"});return}S(c),l(),h(o).then(n=>{if(n.hits.length===0){s.warning({title:"Caution",message:"Sorry, there are no images matching your search query. Please try again!"}),l();return}L(n.hits)}).catch(n=>{console.error("Error fetching data:",n),s.error({title:"Error",message:"Error.",position:"topRight"})}).finally(()=>{q(c)})});
//# sourceMappingURL=index.js.map
